name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Run tests
      run: sbt test
    - name: Package
      run: sbt package
    - uses: actions/upload-artifact@v2
      with:
        path: target/scala-2.13/magmajavabootstrap_2.13-0.1.jar
